### Tensor:
Imagine you have a box that stores numbers. Sometimes it's just one number, sometimes a list, a table, or even a 3D cube.
- A tensor is just like that box, it holds numbers in different shapes.
- In PyTorch and Deep Learning, everything works with these boxes (tensors).
- Tensors are like Python lists or NumPy arrays, but faster and made for training models using GPU and gradients.

#### First of all you have to do installation, if you are using google colab then there is no need to install this.

In [3]:
import torch

#### 1. Scalar
Imagine you got 95 marks in a test, so it is just one number. 
- When we make it a tensor, it becomes a scalar tensor.
- A scalar means just one value. It has no shape.

**Example in Deep Learning:**
When a model gives you the final result like "Loss = 0.27", that’s a scalar.

In [7]:
scalar = torch.tensor(2)
print("We create a scalar tensor with value 2:", scalar)

We create a scalar tensor with value 2: tensor(2)


In [8]:
scalar = torch.tensor(5.0)
print("We create a scalar tensor with value 5.0:", scalar)

We create a scalar tensor with value 5.0: tensor(5.)


In [9]:
scalar = torch.tensor(10)
print("We create a scalar tensor with value 10:", scalar)

We create a scalar tensor with value 10: tensor(10)


#### 2. Vector:
Now think about saving your height, weight, and age, so it looks like: [170, 65, 22]
- This is a vector, a list with many values in a single line. And it is 1D (one-dimension).

**Use Case:**
When you give a model a person’s data or image pixels, you use a vector.



In [11]:
vector = torch.tensor([1.0, 2.0, 3.0])
print("We create a vector tensor with values:", vector)

We create a vector tensor with values: tensor([1., 2., 3.])


In [12]:
vector = torch.tensor([4.0, 5.0, 6.0])
print("We create another vector tensor with values:", vector)

We create another vector tensor with values: tensor([4., 5., 6.])


#### 3. Matrix:
Now think of 3 students and their 3 test scores:
- Student1:  [90, 85, 80] 
- Student2: [88, 82, 84]  
- Student3: [70, 75, 72]

This looks like a table, so we call it a matrix. It has rows and columns. This is a 2D tensor.

**Use Case:**
Model weights and image data are usually in matrix form.

In [13]:
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("We create a matrix tensor with values:\n", matrix)

We create a matrix tensor with values:
 tensor([[1., 2.],
        [3., 4.]])


In [14]:
matrix = torch.tensor([[1, 2], 
                       [3, 4],
                       [4, 5]])
print("We create another matrix tensor with values:\n", matrix)

We create another matrix tensor with values:
 tensor([[1, 2],
        [3, 4],
        [4, 5]])


#### 4. Random Tensor:
Sometimes we start training a model and want the starting values to be random.
- That’s when we use a random tensor, so it fills with numbers between 0 and 1.

**Use Case:**
When a model is new, we give it random values to begin learning.


In [16]:
rand_tensor = torch.rand(3, 3)
print("We create a random tensor with shape (3, 3):\n", rand_tensor)

We create a random tensor with shape (3, 3):
 tensor([[0.8776, 0.8596, 0.4920],
        [0.1756, 0.0485, 0.2699],
        [0.7059, 0.7106, 0.2767]])


In [17]:
rand_tensor = torch.rand(2, 2)
print("We create another random tensor with shape (2, 2):\n", rand_tensor)

We create another random tensor with shape (2, 2):
 tensor([[0.1684, 0.9327],
        [0.1866, 0.6260]])


#### 5. Zeros and Ones
- If we want to start everything from zero, we make a tensor with only zeros.
- If we want to show ON/OFF type data, we can use ones and zeros.

**Example:**
Making a table where 0 = not selected and 1 = selected. This helps in training and creating sample data.

In [18]:
zeros = torch.zeros(2, 3)
print("We create a tensor filled with zeros of shape (2, 3):\n", zeros)

We create a tensor filled with zeros of shape (2, 3):
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [19]:
ones = torch.ones(2, 3)
print("We create a tensor filled with ones of shape (2, 3):\n", ones)

We create a tensor filled with ones of shape (2, 3):
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### 6. range and Tensor Like
**torch.arange()** works like Python’s range(). It creates a line of numbers like: 0, 1, 2, 3, ...

**Example:**
torch.arange(0, 10) will give numbers from 0 to 9. (Last no./Endpoint is excluded).

**torch.tensor_like()** creates a new tensor with the same shape and type as another one.

**Use Case:**
When you want to make a copy with different values inside.

In [20]:
aranged_tensor = torch.arange(0, 10)
print("We create a tensor with numbers from 0 to 9:\n", aranged_tensor)

We create a tensor with numbers from 0 to 9:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [27]:
sample_tensor = torch.tensor([[1, 2], [3, 4]])
sample_tensor

tensor([[1, 2],
        [3, 4]])

In [28]:
tensor_like = torch.ones_like(sample_tensor)
print("We create a tensor like sample_tensor with ones:\n", tensor_like)

We create a tensor like sample_tensor with ones:
 tensor([[1, 1],
        [1, 1]])


In [29]:
tensor_like = torch.zeros_like(sample_tensor)
print("We create a tensor like sample_tensor with zeros:\n", tensor_like)

We create a tensor like sample_tensor with zeros:
 tensor([[0, 0],
        [0, 0]])


#### 7. torch.eye (Identity Matrix)
This is a special matrix with 1s only on the diagonal and 0s everywhere else.
[1 0 0]  
[0 1 0]  
[0 0 1]

**Use Case:**
It's like a mirror. Means what you give in, you get out the same.
Used when we don’t want to change the input.

In [30]:
eye_tensor = torch.eye(3)
print("We create an identity matrix of size 3x3:\n", eye_tensor)

We create an identity matrix of size 3x3:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### 8. torch.full
This makes a matrix where every value is the same.

**Example:**
torch.full((2, 2), 7) makes:
[7 7]  
[7 7]

**Use:**
Useful when you want a default value, like giving all students 10 bonus marks to start.


In [31]:
filled_tensor = torch.full((2, 3), 7)
print("We create a tensor filled with the value 7 of shape (2, 3):\n", filled_tensor)

We create a tensor filled with the value 7 of shape (2, 3):
 tensor([[7, 7, 7],
        [7, 7, 7]])


#### 9. torch.linspace
When we want to get numbers between 0 and 1 with equal gaps.

**Example:**
torch.linspace(0, 1, steps=5) gives:

[0.00, 0.25, 0.50, 0.75, 1.00]

**Use Case:**
Great for drawing graphs or when you want evenly spaced values.

In [34]:
lin_tensor = torch.linspace(0, 1, steps=5)
print("We create a tensor with 5 evenly spaced values between 0 and 1:\n", lin_tensor)

We create a tensor with 5 evenly spaced values between 0 and 1:
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


#### 10. Tensor Data Types
Inside a tensor, the numbers have types, like:
- int -> whole numbers (1, 2, 3)
- float -> decimal numbers (1.0, 2.5)
- bool -> true or false (1 or 0)

**Example:**
- int: Your marks (70, 85, 90).
- float: Your CGPA (3.43, 3.88).
- bool: Pass or Fail (True / False).

**How to do in Pytorch?**
- tensor.int()
- tensor.float()
- tensor.bool() 


In [35]:
int_tensor = torch.tensor([1, 2, 3])
int_tensor, int_tensor.dtype

(tensor([1, 2, 3]), torch.int64)

In [ ]:
#now we convert the int_tensor to float
float_tensor = int_tensor.float()
print("We convert int_tensor to float:\n", float_tensor, float_tensor.dtype)


We convert int_tensor to float:
 tensor([1., 2., 3.]) torch.float32


In [43]:
bool_tensor = torch.tensor([1, 1, 0], dtype=torch.bool)
print("We create a boolean tensor with values:\n", bool_tensor)

We create a boolean tensor with values:
 tensor([ True,  True, False])


#### 11. Getting Tensor Info:
When you create a tensor, you can check:
- Shape -> size (like rows and columns)
- Dtype -> type of numbers (int, float)
- Device -> is it on CPU or GPU?

**Why is it important?**
Before training a model, you must know:
- What size is your data?
- Is the model expecting float or int?
- Are you using GPU or just CPU?

**Example:**
- A grayscale image: shape = [1, 28, 28] -> 1 channel, 28x28 pixels
- If you give shape [28, 28] by mistake -> model can give an error
- Also, checking the device helps when using GPU for faster training

In [44]:
tensor_info = torch.rand(2, 3)
print("We create a random tensor with shape (2, 3):\n", tensor_info)
print("Shape of tensor_info:", tensor_info.shape)
print("Data type of tensor_info:", tensor_info.dtype)
print("Number of dimensions of tensor_info:", tensor_info.ndim)
print("Device of tensor_info:", tensor_info.device)

We create a random tensor with shape (2, 3):
 tensor([[0.2322, 0.4557, 0.7299],
        [0.0248, 0.4395, 0.8647]])
Shape of tensor_info: torch.Size([2, 3])
Data type of tensor_info: torch.float32
Number of dimensions of tensor_info: 2
Device of tensor_info: cpu


##### **Shape Errors:**
When you try to use two tensors together, but their shapes do not match, you get an error.
**Example:**
- Tensor A: shape = [2, 3]
- Tensor B: shape = [3, 2]

You try to multiply them, it gives an error b/c: “shapes don’t match”. You know that in a matrix multiplication, we must make sure that the column of matrix 1 is equal to the rows of matrix 2. It mean in above example the Tensor A shape is "1x2" and tenor B is "1x2". So column of Tensor A is "2" and Row of Tensor B is "1", so it won't do multiplication.

**Example:**
Imagine putting 2 books on a shelf.
- One book is horizontal
- One is vertical

The shelf won’t fit both. same thing happens with wrong shapes.

Most beginner mistakes in training happen because of wrong tensor shapes.
If input and output shapes don’t match, the model won’t work.

**So it's very important to always check the shape.**


In [45]:
Tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

Tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

print("Tensor A:\n", Tensor_A)
print("Tensor B:\n", Tensor_B)

Tensor A:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor B:
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [48]:
#Now we do matrix multiplication
# Tensor_Multiply = torch.matmul(Tensor_A, Tensor_B) #It gives an error b/c of shape mismatch. So we transpose Tensor_B
Tensor_B = Tensor_B.T
Tensor_B

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [55]:
print("Tensor A: ", Tensor_A, Tensor_A.shape)

print("Tensor B: ", Tensor_B, Tensor_B.shape)

Tensor A:  tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])
Tensor B:  tensor([[ 7,  9, 11],
        [ 8, 10, 12]]) torch.Size([2, 3])


In [56]:
Tensor_Multiply = torch.matmul(Tensor_A, Tensor_B)
print("Result of matrix multiplication:\n", Tensor_Multiply)

Result of matrix multiplication:
 tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


#### 12. Reshape, Stack, Squeeze, Unsqueeze, Permute

##### **Reshape:**
When you change how the data looks (like rows and columns), but you don’t change the actual numbers inside the tensor. So reshape() changes the layout (rows × columns) of a tensor without changing the values inside.

**Example:**
Imagine you have 8 laptops in a sinlge row. (L1, L2, ..., L8). Now you put them in a box with 4 rows and 2 columns.
[
    [L1 L2],
    [L3 L4],
    [L5 L6],
    [L7 L8]
]

The laptops are the same. Only the layout changed. This is called **Reshaping**.

In [58]:
sample_tensor = torch.rand(2, 3)
print("Sample tensor with shape (2, 3):\n", sample_tensor)

Sample tensor with shape (2, 3):
 tensor([[0.6516, 0.7299, 0.8049],
        [0.4785, 0.2242, 0.0480]])


In [59]:
reshaped_tensor = sample_tensor.reshape(3, 2)
print("Reshaped tensor to shape (3, 2):\n", reshaped_tensor)

Reshaped tensor to shape (3, 2):
 tensor([[0.6516, 0.7299],
        [0.8049, 0.4785],
        [0.2242, 0.0480]])


##### **Stack:**
When you take two or more tensors with the same size and put them on top of each other like a pile. So it means stack() puts multiple tensors together along a new axis.

**Example:**
You have 3 same-size pages. You make a small book by stacking them.

a = torch.tensor([1, 2])

b = torch.tensor([3, 4])

So, when we stack them **torch.stack([a, b])**, it gives:

[

 [1, 2],

 [3, 4]
 
]



In [64]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
stacked_tensor = torch.stack((a, b))
print("Stacked tensor along dimension 0:\n", stacked_tensor)

Stacked tensor along dimension 0:
 tensor([[1, 2],
        [3, 4]])


In [68]:
a = torch.arange(1., 9.)
print("Sample Tensor with values from 1 to 8:\n", a)

Sample Tensor with values from 1 to 8:
 tensor([1., 2., 3., 4., 5., 6., 7., 8.])


In [70]:
a_stacked = torch.stack((a, a, a, a), dim=0) #Here 0 means add stack row wise. 
print("Stacked tensor:\n", a_stacked)

Stacked tensor:
 tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]])


In [72]:
a_stacked = torch.stack((a, a, a, a), dim=1) #Here 1 means add stack column wise. 
print("Stacked tensor:\n", a_stacked)

Stacked tensor:
 tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])


##### **Squeeze** amd **Unsqeeze**:
**Squeeze:**
When we want to remove dimensions that are just size 1, because they don’t carry useful information. So, it means squeeze() removes any dimension with size 1, like unnecessary space.

**Why we use it?**
- To clean up extra dimensions.
- Makes the data easier to handle for models.

**Unsqueeze:**
It adds a new dimension of size 1 to your tensor. Just the opposite of squeeze. So it means unsqueeze() adds a new dimension (of size 1) to a tensor.

**Why we use it?**
- CNN models need input in 4D: [batch, channel, height, width]
- You can use unsqueeze() to match that format



In [76]:
sample_tensor = torch.arange(1., 9.)
print("Sample tensor with values from 1 to 8:\n", sample_tensor, sample_tensor.shape)

Sample tensor with values from 1 to 8:
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


In [77]:
unsqeezed_sample_tensor = sample_tensor.unsqueeze(0)  # Adds a new dimension at the front
print("Unsqueezed sample tensor:\n", unsqeezed_sample_tensor, unsqeezed_sample_tensor.shape)

Unsqueezed sample tensor:
 tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]) torch.Size([1, 8])


In [79]:
squeezed_sample_tensor = unsqeezed_sample_tensor.squeeze(0)  # Removes the dimension at index 0
print("Squeezed sample tensor:\n", squeezed_sample_tensor, squeezed_sample_tensor.shape)

Squeezed sample tensor:
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


##### **Pemute:**
It rearranges the order of dimensions in your tensor. So it means permute() lets you rearrange the order of tensor dimensions.

**Example:**
In Excel:
- Rows = students
- Columns = subjects

Now, you want to flip it:
- Rows = subjects
- Columns = students

That’s what permute() does.

**Why we use it?**
- For CNNs or image models
- To change shape like [height, width, channels] -> [channels, height, width]
- For NLP tasks to switch batch and sequence positions

In [81]:
sample_tensor = torch.rand(2, 3, 4)
print("Sample tensor with shape (2, 3, 4):\n", sample_tensor, sample_tensor.shape)

Sample tensor with shape (2, 3, 4):
 tensor([[[0.3037, 0.4773, 0.9518, 0.1046],
         [0.9177, 0.4000, 0.1486, 0.8763],
         [0.1339, 0.5291, 0.2863, 0.8404]],

        [[0.6154, 0.7008, 0.8907, 0.9916],
         [0.5517, 0.3638, 0.0082, 0.4867],
         [0.6749, 0.1777, 0.8984, 0.0586]]]) torch.Size([2, 3, 4])


In [82]:
permute_sample_tensor = sample_tensor.permute(2, 0, 1)  # Rearranging dimensions)
print("Permuted sample tensor with shape (4, 2, 3):\n", permute_sample_tensor, permute_sample_tensor.shape)

Permuted sample tensor with shape (4, 2, 3):
 tensor([[[0.3037, 0.9177, 0.1339],
         [0.6154, 0.5517, 0.6749]],

        [[0.4773, 0.4000, 0.5291],
         [0.7008, 0.3638, 0.1777]],

        [[0.9518, 0.1486, 0.2863],
         [0.8907, 0.0082, 0.8984]],

        [[0.1046, 0.8763, 0.8404],
         [0.9916, 0.4867, 0.0586]]]) torch.Size([4, 2, 3])


##### *Working:**
How this works:
1. We create a tensor with shape (2, 3, 4).
2. We permute the dimensions to (4, 2, 3), which means:
    - The first dimension (2) becomes the second dimension (0).
    - The second dimension (3) becomes the first dimension (1).
    - The third dimension (4) becomes the third dimension (2).
3. The resulting tensor has the shape (4, 2, 3), where the dimensions have been rearranged.